"""initial schema

Revision ID: fe17f9484e10
Revises: 
Create Date: 2026-09-03 23:46:52.224331
"""
from alembic import op
import sqlalchemy as sa


revision = 'fe17f9484e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
