# Write the new extensions.py to disk (adds JWT blacklist store)
import pathlib
TARGET = pathlib.Path(__file__).parent.parent / "backend" / "extensions.py"
EXT_LINES = [
    "'''\n",
    "Aurum Ghana - Flask extensions (initialised here, bound to app in app.py)\n",
    "'''\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from flask_jwt_extended import JWTManager\n",
    "from flask_cors import CORS\n",
    "from flask_limiter import Limiter\n",
    "from flask_limiter.util import get_remote_address\n",
    "from flask_bcrypt import Bcrypt\n",
    "from flask_migrate import Migrate\n",
    "\n",
    "db = SQLAlchemy()\n",
    "jwt = JWTManager()\n",
    "bcrypt = Bcrypt()\n",
    "migrate = Migrate()\n",
    "limiter = Limiter(key_func=get_remote_address, default_limits=['100 per hour'])\n",
    "\n",
    "# ─── JWT Token Blacklist (in-memory; swap for Redis in production) ───────────\n",
    "# Set of jti values that have been revoked (logged out or password-changed).\n",
    "_jwt_blacklist = set()\n",
    "\n",
    "\n",
    "def jwt_token_in_blacklist_callback(jwt_header, jwt_payload):\n",
    '    """Return True if the token jti is revoked."""\n',
    '    return jwt_payload["jti"] in _jwt_blacklist\n',
    "\n",
    "\n",
    "def revoke_token(jti):\n",
    '    """Add a token jti to the blacklist."""\n',
    "    _jwt_blacklist.add(jti)\n",
    "\n",
    "\n",
    "def revoke_all_user_tokens(user_jtis):\n",
    '    """Revoke a list of jti values (e.g. all sessions for a user)."""\n',
    "    _jwt_blacklist.update(user_jtis)\n",
]
TARGET.write_text("".join(EXT_LINES), encoding="utf-8")
print(f"Written {TARGET}")

# Write the new security.py to disk
import pathlib
TARGET = pathlib.Path(__file__).parent.parent / "backend" / "utils" / "security.py"
SEC_LINES = [
    "'''\n",
    "Aurum Ghana - Security utilities\n",
    "'''\n",
    "import hashlib\n",
    "import os\n",
    "import re\n",
    "import secrets\n",
    "import urllib.request\n",
    "from functools import wraps\n",
    "from flask import request, jsonify, current_app\n",
    "from flask_jwt_extended import verify_jwt_in_request, get_jwt_identity\n",
    "from backend.models import User\n",
    "\n",
    "# Password Policy (12+ chars, configurable via MIN_PASSWORD_LENGTH env var)\n",
    'MIN_PASSWORD_LENGTH = int(os.getenv("MIN_PASSWORD_LENGTH", "12"))\n',
    "MAX_PASSWORD_LENGTH = 128\n",
    "\n",
    "# HIBP k-anonymity in-process cache\n",
    "_hibp_cache = {}\n",
    "\n",
    "\n",
    "def validate_email(email):\n",
    "    if not email or len(email) > 255:\n",
    "        return False\n",
    '    return bool(re.match(r"^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$", email))\n',
    "\n",
    "\n",
    "def validate_ghana_phone(phone):\n",
    '    """Accept Ghana phone formats: +233XXXXXXXXX, 0XXXXXXXXX, XXX-XXX-XXXX."""\n',
    "    if not phone:\n",
    "        return False\n",
    '    cleaned = re.sub(r"[\\s\\-]", "", phone)\n',
    '    return bool(re.match(r"^(\\+233|0)\\d{9}$", cleaned))\n',
    "\n",
    "\n",
    "def normalize_ghana_phone(phone):\n",
    '    """Normalize to 0XXXXXXXXX (10 digits)."""\n',
    '    cleaned = re.sub(r"[\\s\\-]", "", phone)\n',
    '    if cleaned.startswith("+233"):\n',
    '        return "0" + cleaned[4:]\n',
    "    return cleaned\n",
    "\n",
    "\n",
    "def _check_hibp_k_anonymity(password):\n",
    '    """Check Have I Been Pwned via k-anonymity (only SHA-1 prefix sent to HIBP)."""\n',
    '    sha1 = hashlib.sha1(password.encode("utf-8")).hexdigest().upper()\n',
    "    prefix, suffix = sha1[:5], sha1[5:]\n",
    "    if prefix in _hibp_cache:\n",
    "        return suffix in _hibp_cache[prefix]\n",
    "    try:\n",
    '        url = f"https://api.pwnedpasswords.com/range/{prefix}"\n',
    '        req = urllib.request.Request(url, headers={"User-Agent": "AurumGhana-SecurityCheck/1.0"})\n',
    "        with urllib.request.urlopen(req, timeout=5) as resp:\n",
    '            data = resp.read().decode("utf-8", errors="ignore")\n',
    '        _hibp_cache[prefix] = set(line.split(":")[0] for line in data.strip().split("\\n") if line)\n',
    "        return suffix in _hibp_cache[prefix]\n",
    "    except Exception:\n",
    '        current_app.logger.warning("HIBP API unavailable; skipping breach check")\n',
    "        return False\n",
    "\n",
    "\n",
    "def validate_password_strength(password, check_breach=True, previous_hashes=None):\n",
    '    """Modern password policy: 12+ chars, 1 letter, 1 number. Optional HIBP + reuse check."""\n',
    "    if not password:\n",
    '        return False, "Password is required"\n',
    "    if len(password) < MIN_PASSWORD_LENGTH:\n",
    '        return False, f"Password must be at least {MIN_PASSWORD_LENGTH} characters"\n',
    "    if len(password) > MAX_PASSWORD_LENGTH:\n",
    '        return False, "Password too long"\n',
    '    if not re.search(r"[A-Za-z]", password):\n',
    '        return False, "Password must contain at least one letter"\n',
    '    if not re.search(r"\\d", password):\n',
    '        return False, "Password must contain at least one number"\n',
    '    if check_breach and os.getenv("CHECK_HIBP", "true").lower() not in ("0", "false", "no"):\n',
    "        if _check_hibp_k_anonymity(password):\n",
    '            return False, "This password appeared in a known data breach. Please choose a different one."\n',
    "    if previous_hashes:\n",
    "        from backend.extensions import bcrypt\n",
    "        for old_hash in previous_hashes[-5:]:\n",
    "            if bcrypt.check_password_hash(old_hash, password):\n",
    '                return False, "You cannot reuse a recently used password."\n',
    "    return True, \"\"\n",
    "\n",
    "\n",
    "def generate_csrf_token():\n",
    "    return secrets.token_urlsafe(32)\n",
    "\n",
    "\n",
    "def role_required(*roles):\n",
    '    """Decorator: require JWT identity + active-user + role check. Attaches request.current_user."""\n',
    "    def decorator(fn):\n",
    "        @wraps(fn)\n",
    "        def wrapper(*args, **kwargs):\n",
    "            verify_jwt_in_request()\n",
    "            user_id = get_jwt_identity()\n",
    "            user = User.query.get(user_id)\n",
    "            if not user or not user.is_active:\n",
    '                return jsonify({"detail": "Unauthorized"}), 401\n',
    "            if roles and user.role not in roles:\n",
    '                return jsonify({"detail": "Forbidden", "code": "insufficient_role"}), 403\n',
    "            request.current_user = user\n",
    "            return fn(*args, **kwargs)\n",
    "        return wrapper\n",
    "    return decorator\n",
    "\n",
    "\n",
    "def get_request_meta():\n",
    '    """IP address and User-Agent for audit logging."""\n',
    "    return {\n",
    '        "ip": request.headers.get("X-Forwarded-For", request.remote_addr) or "",\n',
    '        "user_agent": request.headers.get("User-Agent", "")[:500],\n',
    "    }\n",
]
TARGET.write_text("".join(SEC_LINES), encoding="utf-8")
print(f"Written {TARGET}")
